"""Add explanation column

Revision ID: 3e95b8698756
Revises: 8377c4d104a4
Create Date: 2026-10-08 22:11:40.921887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e95b8698756'
down_revision: Union[str, Sequence[str], None] = '8377c4d104a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_predictions', sa.Column('explanation', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_predictions', 'explanation')
    # ### end Alembic commands ###
